### ISSUE TITLE
Unexpected AppendVec

### ISSUE THREAD

**Issue by Dassy23** [terorie/solana-snapshot-etl#18]
Running the tool on a full snapshot gives me this error

user@decompres-test:~/decomp$ solana-snapshot-etl snapshot-*.tar.zst --sqlite-out snapshot.db
[2022-07-13T22:12:38Z INFO  solana_snapshot_etl] Reading snapshot archive
[2022-07-13T22:12:38Z ERROR solana_snapshot_etl] Unexpected AppendVec

**Comment by terorie** [comment]
@Dassy23 What version of Solana produced this snapshot? Could you please send me the first few lines of 

```
zstdcat snapshot-*.tar.zst | tar -tv | head -n100
```

Thanks!

**Comment by terorie** [comment]
Uncompressing the snapshot first and then running the tool against the uncompressed dir should work in any case.

**Comment by Dassy23** [comment]
Ahh this was an issue with the tar file getting corrupted as I moved it around, you can close this issue. Thanks for the quick response, and wicked codebase🤘
